"""2

Revision ID: c32eb84aff46
Revises: 9fb158cd28e1
Create Date: 2024-03-26 02:44:53.506221+07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32eb84aff46'
down_revision = '9fb158cd28e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
